# Generated by Django 4.1.3 on 2022-11-16 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idLibro', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(default=0)),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('numpags', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Libros',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='LibroPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
            ],
            options={
                'verbose_name': 'LibroPrestamo',
                'verbose_name_plural': 'LibroPrestamo',
            },
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('idLibro', models.IntegerField(default=0)),
                ('idUsuario', models.IntegerField(default=0)),
                ('FecPrestamo', models.DateField(verbose_name='Fecha de inicio')),
                ('FecDevolucion', models.DateField(verbose_name='Fecha de fin')),
                ('libro', models.ManyToManyField(blank=True, through='biblioteca.LibroPrestamo', to='biblioteca.libro')),
            ],
            options={
                'verbose_name': 'Prestamos',
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('numUsuario', models.IntegerField(default=0)),
                ('nif', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
            options={
                'verbose_name': 'UsuarioPrestamo',
                'verbose_name_plural': 'UsuarioPrestamo',
            },
        ),
        migrations.AddField(
            model_name='prestamos',
            name='usuario',
            field=models.ManyToManyField(blank=True, through='biblioteca.UsuarioPrestamo', to='biblioteca.usuario'),
        ),
        migrations.AddField(
            model_name='libroprestamo',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamos'),
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
            ],
            options={
                'verbose_name': 'Autores',
                'verbose_name_plural': 'Autores',
            },
        ),
    ]
