# Generated by Django 4.1.3 on 2022-11-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libroprestamo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarioprestamo',
            options={},
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='idLibro',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='idUsuario',
            field=models.CharField(max_length=10),
        ),
    ]
